### ISSUE TITLE
Complex function support?

### ISSUE THREAD

**Issue by ShawnGeller** [risi-kondor/Snob2#2]
I apologize if this is already supported, but I couldn't really tell from the docs. Are Fourier transforms of complex functions supported? Thank you in advance.

**Comment by risi-kondor** [comment]
No, they are not. However, Young's Orthogonal Rerpesentation is a real representation, so transforming a complex function is really the same as transforming its real and imaginary parts separately. The documentation of the C++ API is out of date, BTW.

**Comment by ShawnGeller** [comment]
That makes sense, Thank you! Thanks for the heads up about the docs. Just want to say also: your PhD thesis is an awesome reference!
